### ISSUE TITLE
turning back to Json

### ISSUE THREAD

**Issue by joedaniels29** [thoughtbot/Argo#10]
Is there a recommended way to turn back into JSON? 
Or would it be best to use NSJSONSerialization like so:

``` swift
var params = ["id": id, "name":name, "email":email] as NSDictionary 
var err: NSError?
var stringJSON  = NSJSONSerialization.dataWithJSONObject(params, options: nil, error: &err)
```

**Comment by emilwojtaszek** [comment]
@joedaniels29 I was thinking about it today also and that's my proposition at the moment 
```
public extension JSONValue {
    public static func reverse(j: JSONValue) -> AnyObject {
        switch j {
        case let .JSONNull: return NSNull()
        case let .JSONString(v): return v
        case let .JSONNumber(v): return v
        case let .JSONArray(a): return a.map(reverse)
        case let .JSONObject(v):
            var object: [String: AnyObject] = [:]
            for key in v.keys {
                if let value: JSONValue = v[key] {
                    object[key] = reverse(value)
                } else {
                    object[key] = NSNull()
                }
            }
            return object
        }
    }
}
```

**Comment by tonyd256** [comment]
@emilwojtaszek I don't think there is much of a case for turing a `JSONValue` back into JSON. The point of `JSONValue` is to be an in-between step when parsing from JSON to a model object in order to help the Swift compiler with type inference. There shouldn't be many times where you parse the JSON to a `JSONValue` just to call `reverse` to get it back to JSON. The more usual case is to have a model object you need to save in which chase you can just make the `Dictionary` from the model object directly.
