### ISSUE TITLE
Argonaut

### ISSUE THREAD

**Issue by aschuch** [thoughtbot/Argo#101]
I have just released [Argonaut](https://github.com/aschuch/Argonaut), a framework that aims to  accompany Argo with two main goals in mind:

1. Add helpers to make it more convenient to parse JSON into `JSONDecodeable` models, also support parsing models directly from ReactiveCocoa signals.
2. A collection of extensions for common objets (e.g. `NSURL`, etc.) to be directly used with Argo/Runes.

I am not sure if this should be part of Argo itself, mainly because it is partly dependent on ReactiveCocoa, but I thought I put it out there just in case someone else might find it useful.

What do you think? Looking forward to get your feedback. ✨

**Comment by gfontenot** [comment]
Looks rad!

- Your `mapJSON` function looks super similar to our global `decode` functions that are currently on `master` and will be shipped with 1.0.
- I'm a huge fan of the idea of RAC extensions for Argo. I don't think we'd want to include them in Argo proper, but I'd be really interested in a library that _just_ did that
- Default extensions for common types like `NSURL` are something we've talked about a lot internally. I think we decided against including them in Argo itself, because there are plenty of cases where you'd want to customize that decoding, and we didn't want to add a roadblock to users wanting to do that. But I think shipping those extensions with an external lib is a fantastic idea (and I'd probably use it)

Have you thought about breaking the `NSURL`/`CLLocation` stuff out away from the `RAC` extensions? I'm a huge fan of small micro-frameworks.

I'd love to see more of these kinds of libraries. If they start to show up, We should look at creating some sort of centralized list of helper libs.

**Comment by aschuch** [comment]
Gordon, thanks for your quick feedback. 

* Oh, I haven't been aware that `decode` already made it to master, once 1.0 is out, my `mapJSON` functions are probably not needed any more. 
* I am also a huge fan of small micro-frameworks! I updated the repo, kept the RAC extensions in [Argonaut](https://github.com/aschuch/Argonaut) and created a new micro-framework for common types called [GoldenFleece](https://github.com/aschuch/GoldenFleece) (that's what the Argonauts were looking for after all ⛵️). 

My biggest issue for providing a *framework* for common types is that its basically "all or nothing" and I don't think there is a way to work around that limitation (i.e. override the extension?). I think it should be possible with CocoaPods subspecs, but I am not aware of a way to currently achieve something similar with Carthage.

I know GoldenFleece is just a small start, but I'd love to see some active contributions for other types as well. ⚡️

**Comment by gfontenot** [comment]
Solid naming.

> I am not aware of a way to currently achieve something similar with Carthage.

You could have multiple frameworks in your Xcode project, one for each type, and then an umbrella framework that brings in all of them. That might be a cool experiment.

> I know GoldenFleece is just a small start, but I'd love to see some active contributions for other types as well.

+1

**Comment by tonyd256** [comment]
Love that name!

**Comment by aschuch** [comment]
> You could have multiple frameworks in your Xcode project, one for each type, and then an umbrella framework that brings in all of them. That might be a cool experiment.

Yes, I think that's the way to go. :+1:

**Comment by tonyd256** [comment]
Going to close this for now. Feel free to reopen or open a new issue if you have more questions.
