### ISSUE TITLE
Use `throws` syntax instead of returning `Decoded<T>`?

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#150]
Mixed feelings here, but we _could_ change our `decode` instance methods from `JSON -> Decoded<T>` to `JSON throws -> T`. Decoder instances might look something like so:

```swift
extension User: Decodable {
  static func decode(j: JSON) throws -> T {
    let u = create
      <^> j <| "name"
      <*> j <| "email"
    return try u.value
  }
}
```

This would mean that we add `value :: () throws -> T` as an instance method for `Decoded`

**Comment by MarcoSero** [comment]
:+1: This appears to be the direction Apple is headed.

**Comment by czeluff** [comment]
Big fan of this change. I think following along Apple's standardization of error handling will only help adoption of Argo.

**Comment by terhechte** [comment]
Fundamentally, `throws` is just syntactic sugar over an Either type, too. However, right now there's not a good way of accessing Errors in any way except via do/try/catch. Apparently, one of the next Swift betas will bring support for handling errors as Either types: https://twitter.com/jckarter/status/608002431578865664

I think it might be wise to wait for this change and see what that Either type is going to look like. The current downside with throws, that I see, is that one looses a lot of syntactic flexibility:

With throw, the only available syntax to handle an error is via

```
do { try something}
catch ... { something else}
```

While the Result type offers the flexibility of using `if let`, `switch`, `guard`, `map`, `apply`, and `flatMap` in order to handle the error case.

**Comment by gfontenot** [comment]
I'm going to close this in favor of the discussion in #153
