### ISSUE TITLE
Using Argo with iOS 7?

### ISSUE THREAD

**Issue by kremizask** [thoughtbot/Argo#160]
I want to use Argo on my project which has deployment target iOS 7. Since iOS 7 does not support embedded frameworks I used submodules to include the dependency in my repo and just linked the source files in my project. I also did the same with the Runes and Box repos.

However I ran into 2 problems:
1. Both Argo and Runes have a file named Operators.swift which creates a collision.
2. The compiler complains for the import Runes lines ("No such module 'Runes'") because I am using just the source files in my project and not the framework.

Is there a workaround around these issues?

**Comment by jshier** [comment]
Having the same requirements, I've decided that, ideally, you would fork Argo and Runes, make the changes you need, and set the submodules to point to your forks. Every so ofter you would need to sync your fork, but otherwise should be the same as your current setup.

**Comment by jshier** [comment]
@kremizask I just heard about [CocoaSeeds] (https://github.com/devxoul/CocoaSeeds), which I may try over the long weekend. You'd still have to fork and make modifications, but at least the project integration would be automatic. And no submodules!

**Comment by jshier** [comment]
@kremizask I've successfully used CocoaSeeds to install Argo and Runes. After reporting the duplicate file name issue to the CocoaSeeds creator, he created a flag which can be used to prefix the project name to the file name, solving the issue. As for `import Runes`, I've asked the CocoaSeeds creator about pre and post scripts, but it's simple enough to run `seed install` and then do a find and replace on `import Runes` to delete the lines that it may not be worth the effort. Manual Swift installs are always going to be tricky, as Swift is intended for use with frameworks and you may run into filename or symbol conflicts otherwise.

**Comment by tonyd256** [comment]
@kremizask Thanks for helping out here. We're not planning to support iOS 7 so it's nice to know that there is a workaround that is doable with a bit of extra work.

**Comment by kremizask** [comment]
@jshier Thank you very much for your help! I will give CocoaSeeds a try!

**Comment by devxoul** [comment]
@kremizask, you can install Argo and Runes with Seedfile:

```ruby
github "thoughtbot/Argo", "v2.1.0", :files => "Argo/**/*.swift"
github "thoughtbot/Runes", "v3.0.0", :files => "Source/**/*.swift"
```
