### ISSUE TITLE
Build errors w/ Xcode 7b5

### ISSUE THREAD

**Issue by gsimmons** [thoughtbot/Argo#188]
In Array.swift.

**Comment by tonyd256** [comment]
@gsimmons There is no `Array.swift` file in the Swift 2.0 branch of Argo. I just ran the tests and Argo builds and passes tests just fine in Xcode 7 b5 on the Swift 2.0 branch. I'm closing this issue because I'm not seeing any build errors. If you are still having issues please create a new issue with more detail about what is happening.

**Comment by gsimmons** [comment]
Sorry! It's in the Runes project.
