### ISSUE TITLE
Serialization (encode) as well?

### ISSUE THREAD

**Issue by angerman** [thoughtbot/Argo#206]
Are there plans to add the inverse: Object -> JSON (or a type that NSJSONSerialization can serialze) as well?

**Comment by paulyoung** [comment]
@angerman this has been discussed quite a bit in #139.

I've been using @edwardaux's [Ogra](https://github.com/edwardaux/Ogra) for encoding.

**Comment by angerman** [comment]
Ahh nice. Maybe there should be alink to Ogra from the README then?

**Comment by AlexanderKaraberov** [comment]
Or may be it is a better to include `Encodable` from Ogra right in the Agro library. Because it is a very often task to parse back from model into JSON.

**Comment by gfontenot** [comment]
Ogra is fantastic, and we're big fans. But we don't think that encoding to the `JSON` enum is worth pulling into Argo itself.

We've said this a number of times, but realistically, any time we've needed to encode a value, we've wanted to go directly to `[String: AnyObject]` so that we can pass it directly to `NSJSONSerialization`, not to `JSON`. `JSON` is an intermediary step needed to help the compiler with type inference, it's not intended to be used beyond that.

Realistically, if we added _anything_ to Argo, it'd be a simple `Encodable` protocol that looks like so:

```swift
protocol Encodable {
  func encode() -> [String: AnyObject]
}
```

Then your implementations would look something like

```swift
extension User: Encodable {
  func encode() -> [String: AnyObject] {
    return [
      "email": email,
      "name": name
    ]
  }
}
```

and so on. We don't think that this fits in line with Argo's value proposition (type-safe JSON decoding), and is trivial enough that it doesn't seem worth locking people in.

**Comment by angerman** [comment]
From personal experience, encoding into `JSON` instead of `[String:AnyObject]` has it's benefits. AnyObject is just a pain to work with. Take for example Amazons typed JSON, they use for DynamoDB. Where `[1,2,3]` is turned into `{"L":[{"N":"1"},{"N","2"},{"N","3"}]}` (e.g. we have a `L`ist of `N`umbers). These kind of transformations are much easier to be performed on the JSON object.

Say something like `func toAWSJSON(json:JSON) -> JSON`.

In essence, if you ever need to do some transformation on top of the models JSON representation, `[String:AnyObject]` erases a lot of information.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this as it's not really something we're looking at. I'd highly suggest looking into something like [Ogra](https://github.com/edwardaux/Ogra) if you're looking for this kind of functionality. It's built on top of Argo so moving back and forth should be seamless.
