### ISSUE TITLE
Is there any way to parse a generic type `T`, conforming to `Decodable` protocol with <| operator ?

### ISSUE THREAD

**Issue by AlexanderKaraberov** [thoughtbot/Argo#251]
Here is my model:

```swift
struct GenericServerResponse <T where T: Encodable, T: Decodable> {
    
    let status: String
    let errors: [String]
    let debugErrors: [String]
    let data: T
}

extension GenericServerResponse: Decodable {
    
    static func create
        (status: String)
        (errors: [String])
        (debugErrors: [String])
        (data: T)     -> GenericServerResponse {
            
            return GenericServerResponse(status: status, errors: errors, debugErrors: debugErrors, data: data)
            
    }
    
    static func decode(j: JSON) -> Decoded<GenericServerResponse> {
        return GenericServerResponse.create
            <^> j <|  "status"
            <*> j <|| "errors"
            <*> j <|| "debug_errors"
            <*> j <|  "data"  //Here is an error
    }
}
```
I got error `Ambiguous reference to member <|`. I think I made some kind of stupid error here, or may be it is some kind of limitation in Swift compiler (e.g. because it doesn't support higher kinded types)? Then any possible workarounds?. The reason for this: `data` field can contain any object type which is `Decodable`, for different type of requests and I don't want to duplicate this model for every request with different `data`.

`P.S` Should be marked with `question` label.

**Comment by gfontenot** [comment]
I don't know how this would work, but I'm not sure who's limitation it is. I guess in theory it's the Swift type system, although I don't know how it would figure this out either. You just have a really ambiguous structure here. You need _some_ indication of what you're trying to parse, there's no real way for Argo to be able to figure it out on its own.

**Comment by tonyd256** [comment]
Ya, unfortunately I think `T` is too generic to work here because Argo doesn't know what do decode that as. Would you be able to hold onto `data` as a `JSON`? Then you can decode that when the time comes to the appropriate model. Looking at your example more closely, I think that makes sense. I like how your abstracting a server response. I would just hold on to the `JSON` and then decode to the appropriate model later on down the pipeline.

**Comment by jshier** [comment]
@AlexanderKaraberov In a similar scenario, I do as @tonyd256 suggested and hold onto the parsed JSON.
```swift
struct CloudFlareResponse {
    let result: JSON
    let success: Bool
    let errors: [CloudFlareResponseError]
    let messages: [CloudFlareMessage]
}

extension CloudFlareResponse : Decodable {
    static func decode(json: JSON) -> Decoded<CloudFlareResponse> {
        return curry(self.init)
            <^> json <| "result"
            <*> json <| "success"
            <*> json <|| "errors"
            <*> json <|| "messages"
    }
}
```
Then, since I'm using Alamofire, I use a custom `ResponseSerializer` to decode this response type, check for success, and then decode my generic response object type from the `JSON` already stored.

**Comment by gfontenot** [comment]
I'm going to close this for the sake of cleanliness, but please feel free to continue discussing if there's still a question here.

**Comment by AlexanderKaraberov** [comment]
@gfontenot  Yes I agree that this should be closed. I ended up with @tonyd256 solution.
