### ISSUE TITLE
How to decode String to NSDate using two formats?

### ISSUE THREAD

**Issue by eimantas** [thoughtbot/Argo#268]
All, I have a date extension to make strings decodable into `NSDate` objects. However the problem is that I can do that for only one format like this:

    extension NSDate: Decodable {
        static var dateFormatter: NSDateFormatter {
            let df = NSDateFormatter()
            df.dateFormat = "yyyy-MM-dd"
            return df
        }

        public static func decode(json: JSON) -> Decoded<NSDate> {
            switch(json) {
            case .String(let dateString):
                if let date = dateFormatter.dateFromString(dateString) {
                    return pure(date)
                } else {
                    return Decoded<NSDate>.typeMismatch("date", actual: dateString)
                }
                default:
                    return Decoded<NSDate>.typeMismatch("date", actual: json.description)
            }
        }
    }

Note that this way I can decode the strings of format "yyyy-MM-dd". However in single JSON payload I can have multiple date formats, and I would still like to decode them all into `NSDate` objects. How would I go about achieving this? One way is to create one `NSDateFormatter` instance for every format, however this doesn't feel right because the date decoding would be of trial&error style. Any other suggestions are more than welcome!

**Comment by paulyoung** [comment]
@eimantas check out [this date formatter](https://github.com/thoughtbot/Argo/blob/b0b6920e5c34591e3884a4e50a740167e6cbaf68/Argo%20Playground.playground/Pages/iTunes%20Example.xcplaygroundpage/Contents.swift#L26-L34) and [how to use it](https://github.com/thoughtbot/Argo/blob/b0b6920e5c34591e3884a4e50a740167e6cbaf68/Argo%20Playground.playground/Pages/iTunes%20Example.xcplaygroundpage/Contents.swift#L59) in [this playground](https://github.com/thoughtbot/Argo/blob/b0b6920e5c34591e3884a4e50a740167e6cbaf68/Argo%20Playground.playground/Pages/iTunes%20Example.xcplaygroundpage/Contents.swift).

Instead of `jsonDateFormatter` you could have one for each date format you need to deal with.

**Comment by paulyoung** [comment]
There's also some discussion in https://github.com/thoughtbot/Argo/issues/131 on how to do this.

**Comment by eimantas** [comment]
@paulyoung this allows decoding the date only of single format "yyyy-MM-dd'T'HH:mm:ssz".

What if the same payload contains only date and date time (e.g. "2015-10-15" and "2015-10-15T03:15:14Z")?

**Comment by paulyoung** [comment]
Something like:

```swift
let fooDateFormatter: NSDateFormatter = {
  let dateFormatter = NSDateFormatter()
  dateFormatter.dateFormat = "..."
  return dateFormatter
}()

let barDateFormatter: NSDateFormatter = {
  let dateFormatter = NSDateFormatter()
  dateFormatter.dateFormat = "..."
  return dateFormatter
}()

let fromFooToNSDate: String -> Decoded<NSDate> = {
  .fromOptional(fooDateFormatter.dateFromString($0))
}

let fromBarToNSDate: String -> Decoded<NSDate> = {
  .fromOptional(barDateFormatter.dateFromString($0))
}

extension Baz: Decodable  {
  static func decode(j: JSON) -> Decoded<Baz> {
    return curry(self.init)
      <^> (j <| "fooDate" >>- fromFooToNSDate)
      <*> (j <| "barDate" >>- fromBarToNSDate)
  }
}
```

**Comment by tonyd256** [comment]
@eimantas, What @paulyoung is suggesting is the way to go here. Instead of making `NSDate` conform to `Decodable`, make 2 functions that can decode the different types of formats and use those as shown above. And make sure to have the formatters created outside the parsing functions so that they aren't recreated each time you parse a date.

**Comment by eimantas** [comment]
Ah, now I get it. Thanks for the solution!
