### ISSUE TITLE
Cannot convert value of type

### ISSUE THREAD

**Issue by AndrewSB** [thoughtbot/Argo#294]
Hey!
First time using Argo, so I apologize in advance if this is super obvious, but I am having an issue initializing an object from JSON, getting an error message that isn't completely clear to me.
```swift
struct Video {
    let id: String
    
    let prettyUrl: NSURL
    let url: NSURL
    
    let title: String
    let description: String
}

extension Video: Decodable {
    static func decode(j: JSON) -> Decoded<Video> {
        let f = curry(Video.init)
        return f
            <^> j  <| "id"
            <*> j <| "src_url"
            <*> j <| "converted_src_url"
            <*> j <| "title"
            <*> j <| "description"
    }
}
```

I'm being told (on the `return f` line) that I cannot convert the value to an expected type `_ -> _`
<img width="459" alt="screen shot 2015-11-12 at 8 02 32 pm" src="https://cloud.githubusercontent.com/assets/3814772/11138533/55979ba2-8978-11e5-9640-48813342b424.png">

**Comment by jshier** [comment]
Unless you've added your own `decode` for `NSURL`, that's likely the issue.

**Comment by paulyoung** [comment]
@AndrewSB take a look at https://github.com/the-grid/Disc/blob/b96b213af106c83dabe7f05eaac31817d24928e1/Disc/Models/Extensions/NSURL.swift if you're not sure about how to do that.

**Comment by AndrewSB** [comment]
Yup, that was it. Thanks @jshier and @paulyoung

**Comment by eestein** [comment]
I'm sorry if I don't understand the problem here :/
I have the same issue, here's my code:

```
import Argo
import Curry

struct UserInformation {
    let Pin: String?
    let TransactionId: Int64?
    let TransactionVehicleId: Int64?
    let PhoneNumber: String?
    let VehicleCount: Int?
    let FullName: String?
    let Email: String?
    let DefaultVehicleId: Int64?
    let TransactionStatus: Int?
}

extension UserInformation: Decodable {
    static func decode(json: JSON) -> Decoded<UserInformation> {
        return curry(UserInformation.init)
            <*> json <|? "Pin"
            <^> json <|? "TransactionId"
            <^> json <|? "TransactionVehicleId"
            <*> json <|? "PhoneNumber"
            <^> json <|? "VehicleCount"
            <*> json <|? "FullName"
            <*> json <|? "Email"
            <^> json <|? "DefaultVehicleId"
            <*> json <|? "TransactionStatus"
    }
}
```

I tried to comply with the example provided here https://github.com/thoughtbot/Argo
But I get an error:

![screen shot 2016-04-03 at 15 41 26](https://cloud.githubusercontent.com/assets/2049255/14234167/8e249704-f9b2-11e5-86dd-8e0b4aa16a39.png)

As far I could understand from the conversation above, the issue was related to serializing a complex type I'm assuming Argo wouldn't know how to, right?
If so, that's not my case since I'm only using primitive types. Would you guys be able to help me?

Thanks!
