### ISSUE TITLE
Reasoning behind DecodedType

### ISSUE THREAD

**Issue by RuiAAPeres** [thoughtbot/Argo#303]
On your Decodable.swift file, if I replace this:

```
public protocol Decodable {
  typealias DecodedType = Self
  static func decode(json: JSON) -> Decoded<DecodedType>
}
```

by 

```
public protocol Decodable {
  static func decode(json: JSON) -> Decoded<Self>
}
```

And then make the necessary fixes in the rest of the codebase (basically removing the `T == T.DecodedType` constrain), the library will compile. I was wondering the reasoning (pretty sure I am missing something)  behind this decision.

**Comment by gfontenot** [comment]
That typealias is specifically there to help deal with non-`final` classes. Which sucks.

If you remove all of that and then remove the typealias from `NSURL` in the tests, you _should_ see the compiler fail because it can't guarantee that `Self` is `NSURL` (because it might have been subclassed so `Self` might be `MySuperCoolURLSubclass` and then the type of `decode` would be incorrect).

If that _isn't_ the case, please let me know because I find that hack insanely frustrating.

**Comment by RuiAAPeres** [comment]
Ah yeah, true, `NSURL` will complain! :disappointed:. Thanks Gordon.

**Comment by gfontenot** [comment]
Damn, I was seriously hoping that you'd come back confused because it still compiled.

**Comment by RuiAAPeres** [comment]
@gfontenot all hopes shattered. On the bright side, I was using the same approach and now I can remove it. :stuck_out_tongue:

**Comment by keith** [comment]
Without this type constraint you also have issues with things like `NSDateFormatter` which will always return an `NSDate`, meaning it isn't compatible with `-> Self` for this use case.

**Comment by RuiAAPeres** [comment]
@keith what do you mean: 

> NSDateFormatter which will always return an NSDate

**Comment by keith** [comment]
For example if you wanted to make `NSDate` conform to this and you wanted to create a `NSDate` from a string using `dateFromString:` you'd have a problem if this typealias wasn't there. Since `dateFromString:` returns a `NSDate` which doesn't work with `Self` here.

**Comment by gfontenot** [comment]
Right, as in `decode` wouldn't return an object of the type `NSDateFormatter` (`Self`), it'd return `NSDate`.

Although, we're explicitly disallowing that kind of use with our type constraints (`T.DecodedType == T`).
