### ISSUE TITLE
Cannot parse an model without Id field

### ISSUE THREAD

**Issue by nhatlee** [thoughtbot/Argo#306]
Let assumed that I have an Object with info like: 
"messageInfo": {
      "totalUnReadMessage": "1",
      "totalReadMessage": "0"
      ...
    }
I cannot have an model like that, cause the library require the ID field, and if I have model with ID but server not response the Id field then the app crash. :( please help me

**Comment by paulyoung** [comment]
@nhatlee could you explain which library you're using that requires an ID field, and maybe share some code from your model?

I'm surprised that you're experiencing a crash if decoding with Argo fails. Are you force-unwrapping an optional somewhere?

**Comment by nhatlee** [comment]
@paulyoung I use Argo and Curry to parse json. Here is an example of the model
struct UserModel {
    //General fields
    let user_Id: Int?
    let user_Email: String?
    let user_FirstName: String?
    let user_MemberToken: String?
   .....
}

and decode:
extension UserModel: Decodable{
    static func decode(json: JSON) -> Decoded<UserModel> {
        let user = curry(UserModel.init)
            <^> json <|? KEY_API_ID
            <*> json <|? KEY_API_EMAIL
            <*> json <|? KEY_API_FIRST_NAME
           .....
}

If I want to decode the model, my model need have variable id with type int

**Comment by tonyd256** [comment]
@nhatlee Argo does not require that your models have anything. It is up to you to make your models how you want them. Then use Argo to decode them appropriately. I recommend you read some of the Documentation docs. 

As an example, to decode the object you proposed here `messageInfo`, you should first make the model like so:
```swift
struct MessageInfo {
  let totalUnReadMessage: String
  let totalReadMessage: String
}
```
I used `String`s here because the JSON above uses strings, but you might want to use `Int`s instead.

Then you can use Argo to decode the JSON into those models like so:
```swift
extension MessageInfo: Decodable {
  static func decode(j: JSON) -> Decoded<MessageInfo> {
    return curry(MessageInfo.init)
      <^> j <| "totalUnReadMessage"
      <*> j <| "totalReadMessage"
  }
}
```
Also, the keys above in the `decode` function do not need to be named the same as the properties on `MessageInfo`; however, they do need to be in the same order.

**Comment by nhatlee** [comment]
@tonyd256 Thanks for your advice, It's worked. My problem is I always keep in mind that <^> mean that parse for Int type and <*> parse for string type.

**Comment by tonyd256** [comment]
@nhatlee Glad you got it working. Those operators are Generic and don't care what the type they're operating on as long as it satisfies the type signature of the function. Without getting into what they mean, `<^>` will typically be used for the first parameter when decoding and `<*>` will be used for every parameter after that. Although, these operators employ powerful and really interesting concepts. If you'd like to learn more check out Runes: https://github.com/thoughtbot/Runes

I'll close this for now. Feel free to start a new issue if you have other questions.
