### ISSUE TITLE
Having a [String: AnyObject] property

### ISSUE THREAD

**Issue by yigitcanyurtsever** [thoughtbot/Argo#318]
Hi,

I've been using Argo for a while and I am loving it so far. As I am still in the learning phase, I got stuck on a point. I couldn't find any issue about this.

I have a SocketEvent struct which has metadata property. It could be anything from a project to a comment. I don't want to have a lot of optionals, so I want to keep it as `[String: AnyObject]`. Thus, it shouldn't be decoded. I just want to pass it as it is in `JSON` when using `decode` function of SocketEvent.

```
struct SocketEvent {
    let userIdentifier: String
    let projectIdentifier: String
    let metadata: [String: AnyObject]
}
```

**Comment by tonyd256** [comment]
Hi @yigitcanyurtsever,

So I think you could do a couple things. The easiest might be to type `metadata` as `[String: JSON]`, then when you need to decode later on into a comment or project model you can use that `JSON` value. If you'd still prefer to have an `AnyObject` type there you could implement `Decodable` for `AnyObject` where you just return the value from any of the `JSON` cases. Then when you need to decode later on into your model you can run the `AnyObject` through `JSON.parse` again to get back the `JSON` type for decoding.

I think the first way is better because the second way is undoing then redoing work that's already done.

**Comment by yigitcanyurtsever** [comment]
Hi @tonyd256, 

Thanks for the answer. I actually tried the second way before opening this issue, but apparently we can't extend `AnyObject`. This error shows up when trying to do so `'AnyObject' protocol cannot be extended`.

I'll just go with the first way. Again, thanks for the suggestions. I'm closing the issue.
