### ISSUE TITLE
Warning for Swift 3.0

### ISSUE THREAD

**Issue by jamesdo** [thoughtbot/Argo#335]
`Curried function declaration syntax will be removed in a future version of Swift; use a single parameter list`

We are getting this warning in Swift 2.2, XCode Version 7.3. This is going to be problematic for large classes that are being decoded as `curry` is not working with them yet. The `create` function in the `Decodable` class will not work with the `decode` function if it's not curried.

However, if someone can point me in the direction of some information on decoding large classes (let's say approximately a class with approximately 20 fields) using the new `curry` library, then this problem can be avoided. I did not have luck migrating to `curry` when it was first released and had to default back to the curried `create` function. Any information on this would be great. Thanks !

**Comment by gfontenot** [comment]
@jamesdo Is this still an issue for you?

**Comment by edwardaux** [comment]
I can't speak for @jamesdo, but I can say it fixed it for me.

As a sidenote, the indentation of the braces is important otherwise you will get another warning saying `Expression following 'return' is treated as an argument of the 'return'`. The first `{` must be indented at least one indent level from the `return` statement.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
