### ISSUE TITLE
How to parse JSON Array of Optionals

### ISSUE THREAD

**Issue by bhargavg** [thoughtbot/Argo#360]
Hi, I'm trying to parse:

```json
{
  "id": 1,
  "name": "Cool User",
  "email": "u.cool@example.com",
  "skills": [
    null,
    "paiting",
    "drawing"
  ]
}
```

>Please note that there is a `null` value in `skills` key

My Model:

```swift
struct User {
  let id: Int
  let name: String
  let email: String?
  let skills: [String?]
}
```

I'm getting error:
```swift
cannot invoke 'curry' with an argument list of type '((id: Int, name: String, email: String?, skills: [String?]?) -> User)'
```

Basically, I want to parse an array of optional values.

Does Argo support this?

**Comment by gfontenot** [comment]
Great question! This is totally possible, but means digging into the plumbing a bit and writing a custom decode function.

In short, what we _need_ is a function with the type signature `JSON -> Decoded<[T?]>`. We don't provide this by default. Instead, what we provide (exposed through `<||`) is `JSON -> Decoded<[T]>`, which (as you've noted) is an all or nothing operation.

Looking at `<||` a bit, you will notice that we're using `Array<A>.decode` for the actual heavy lifting. That comes from an extension on `CollectionType` that looks like so:

```swift
public extension CollectionType where Generator.Element: Decodable, Generator.Element == Generator.Element.DecodedType {
  static func decode(j: JSON) -> Decoded<[Generator.Element]> {
    switch j {
    case let .Array(a): return sequence(a.map(Generator.Element.decode))
    default: return .typeMismatch("Array", actual: j)
    }
  }
}
```

So this implementation checks the type of the `JSON` to make sure it's an `.Array`, pulls out the associated value (which is of the type `[JSON]`), then `map`s over _that_ collection to apply the element's `decode` function. We then pass that value (now of type `[Decoded<T>]`) to `sequence`, which transforms it to `Decoded<[T]>`. This is the point that the `decode` operation becomes an all or nothing affair. So up till `sequence`, we're on the right track for what you want to do.

So that gives us a good starting place. We can start by writing this as a free function without the use of `sequence`:

```swift
func decodeOptionalArray<T: Decodable where T.DecodedType == T>(j: JSON) -> [Decoded<T>] {
  switch j {
  case let .Array(a): return a.map(Generator.Element.decode)
  default: return []
  }
}
```

(Note that we're losing our failure info here and instead returning an empty array if we haven't been handed `JSON.Array`. We'll get that back in a bit.)

Now that we have `[Decoded<T>]`, we can try to move to `[Optional<T>]`. We actually expose `Decoded.value`, which transforms a `Decoded` type into an `Optional`, so we can write a small helper function to abstract the idea of performing that transformation on an existing array:

```swift
func values<T>(xs: [Decoded<T>]) -> [T?] {
  return xs.map { $0.value }
}
```

and then we can update our `decodeOptionalArray` function to use it:

```swift
func decodeOptionalArray<T: Decodable where T.DecodedType == T>(j: JSON) -> [T?] {
  switch j {
  case let .Array(a): return values(a.map(Generator.Element.decode))
  default: return []
  }
}
```

Now we're one small jump away from our goal type of `JSON -> Decoded<[T?]>`. Since we don't need to deal with failure states inside the array, we can pass the result directly to `pure`, which wraps a value in `Decoded.Success`. This also means we can re-introduce our failure state if we weren't passed `JSON.Array` as an argument:

```swift
func decodeOptionalArray<T: Decodable where T.DecodedType == T>(j: JSON) -> Decoded<[T?]> {
  switch j {
  case let .Array(a): return pure(values(a.map(Generator.Element.decode)))
  default: return .typeMismatch("Array", actual: j)
  }
}
```

And now we can use it inside our model `decode` function the way we would any other custom transformation function:

```swift
<*> (j <| "key" >>- decodeOptionalArray)
```

**Comment by gfontenot** [comment]
@bhargavg Does this help solve your issue? Can this be closed? Do you have any other questions?

**Comment by bhargavg** [comment]
Yes, thanks for the help.
