### ISSUE TITLE
Parsing different types in the same node for different items

### ISSUE THREAD

**Issue by mribeiro** [thoughtbot/Argo#368]
I'm parsing an API which JSON responses are the greatest but sadly I cannot change it.
So, I have an array and the "in_library" node can bring a `false` (Bool) or an object that, inside, has a "status" as a String.
I want to parse that "in_library" node and, if it is an object, get the value in "status". If "in_library" is `false` I don't mind having it as `nil`.

### Error Messages

Not any error actually, I'm trying to figure a way to do this.

### Sample JSON

With "in_library" as an object (trimmed the JSON just to keep this):
```
"in_library": {
			"status": "done",
```

With "in_library" as Bool (not hard to guess)

```
"in_library": false,
```
### Models

I believe it is not relevant, although I'm using classes so I can have inheritance

### Argo Version

Argo 3.0.1

### Dependency Manager

Cocoapods

**Comment by gfontenot** [comment]
oof. Mismatched types in JSON are usually a bad time.

The specific issue here is that while missing keys are a failable parsing operation, type mismatches are _not_. This means that you won't be able to do something like `j <|? ["in_library", "status"]`. which _would_ work if `in_library` consistently held a dictionary. But since it isn't, you'd get a type mismatch while trying to access `"status"` and so the operation would fail.

Luckily for us,. we actually have a pretty straightforward way out with `<|>`! We can use alternative here (along with `<|?` to make the initial parsing completely failable while providing a sane default in case the key doesn't hold a dictionary. You can use this like so:

```swift
// in your decode function
<*> (j <|? ["in_library", "status"]) <|> pure(.None)
```

So the left hand side tries to parse out the `status` key from the `in_library` dictionary, and succeeds _unless_ the `in_library` key holds something other than a dictionary. In that case, we fall back to the right hand side, which simply returns `.None` wrapped in `Decoded.Success`.

**Comment by jshier** [comment]
Another option is, if you've got a type like this:
```swift
enum InLibraryStatus { // or whatever it's called
    case Done
    case NotDone
    case NotInLibrary
}
```
You can create a custom `decode` for it, which checks if the value is a `Bool` or `Object`, and parses the enum value based on those.

**Comment by gfontenot** [comment]
yep, that's also a great idea and would allow you to avoid the optional property.

**Comment by mribeiro** [comment]
Thanks for the idea guys!
In truth, I'm converting the status to an enum with this implementation (I actually reached an answer before seeing your feedback):

```
enum MovieStatus: Decodable {
    
    case Waiting
    case Downloaded
    case NotDownloaded
    
    static func fromString(string: String?) -> MovieStatus {
        var status: MovieStatus = .NotDownloaded
        if string == "active" {
            status = .Waiting
        } else if string == "done" {
            status = .Downloaded
        }
        return status
    }
    
    static func decode(json: JSON) -> Decoded<MovieStatus> {
        switch json {
        case .Bool:
            return pure(.NotDownloaded)
            
        case .String(let string):
            return pure(MovieStatus.fromString(string))
            
        default:
            
            let stringStatus = curry("".stringByAppendingString)
                <^> json <| "status"
            
            let status = MovieStatus.fromString(stringStatus.value!)
            let pureStatus = pure(status)
            return pureStatus
        }
    }
}
```

basically, on my default, I'm assuming it is an object. I don't expect anything different so it should be fine. However, I think it is more failure prone when comparing to the usage of `<|>`. In any case, I'll need some sort of decode function for the `MovieStatus`.

Thanks for the help guys! very very helpful

**Comment by mribeiro** [comment]
@gfontenot Any documentation on all the available operators, how they can be used and so on? Or is that the documentation still in //TODO in the repo?

**Comment by gfontenot** [comment]
As of Argo 3.0 we have inline documentation for (I believe) the full public interface. You can see it generated [on CocoaDocs](http://cocoadocs.org/docsets/Argo/3.0.1/)
