### ISSUE TITLE
when parase datas(from net) error, how could i find the error? could print error automatic

### ISSUE THREAD

**Issue by OHeroJ** [thoughtbot/Argo#371]

**Comment by gfontenot** [comment]
I'm not 100% sure what you're asking, but I think you might be asking how to print the reason for decoding failures? If so, you can get to this info by decoding to `Decoded` instead of `Optional` and then printing the result. I'd have to see more of your code to be able to give you more direction than that, unfortunately.

**Comment by OHeroJ** [comment]
thank you! i get the  error now
