### ISSUE TITLE
Operator implementation (Xcode 8 beta issues)

### ISSUE THREAD

**Issue by testzugang** [thoughtbot/Argo#386]
Do you expect the current master (188fb11) to work with Xcode 8 beta?
Although Argo's master branch is mentioned to be compatible to Swift 3 there are some issues popping up in Xcode beta. E.g.:

**Operator implementation without matching operator implementation** (Decoded.swift)
```
public func >>- <T, U>(x: Decoded<T>, f: @noescape (T) -> Decoded<U>) -> Decoded<U> {}

public func -<< <T, U>(f: @noescape (T) -> Decoded<U>, x: Decoded<T>) -> Decoded<U> {
```

**Operator is not a known binary** (Decode.swift)
````
return flatReduce(keys, initial: json, combine: decodedJSON) >>- A.decode
```

Argo was added to my project via Cocoapods:
`pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :commit => '188fb11'`

**Comment by tonyd256** [comment]
@testzugang We did update Argo for Swift 3 and Xcode 8 beta. It appears to me that the problem you are seeing is because Runes was not installed properly as a dependency. This should happen automatically for you when using Carthage or Cocoapods. It is possible that the latest master commits aren't working with Cocoapods. I'll take a look and see if that is true.

**Comment by gfontenot** [comment]
@testzugang If you're going to manually specify the git location like that you also need to specify `:submodules => true` or else CocoaPods won't pull down the Runes source that it needs.

```
pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :commit => '188fb11', :submodules => true
```

**Comment by gfontenot** [comment]
I'm closing this as Swift 3.0 support (and a reworking of our Runes dependency) is currently under development.
