### ISSUE TITLE
Need help with a small change.

### ISSUE THREAD

**Issue by matthijsotterloo** [thoughtbot/Argo#387]
Hi there!

I'm using this small piece of code:

```swift
    static func create(api_key: String)(id: Int)(urlString: String?) -> Sharing {
        return Sharing(api_key: api_key, id: String(id), urlString: urlString)
    }
    
    static func decode(j: JSON) -> Decoded<Sharing> {
        return Sharing.create
            <^> j <| "api_key"
            <*> j <| "id"
            <*> j <|? "urlString"
    }
```

when I change the static func called create as suggested by xcode because the way I used it is deprecated, an error pops up. I change the function to:

```swift
static func create(api_key: String, id: Int, urlString: String?) -> Sharing {
      return Sharing(api_key: api_key, id: String(id), urlString: urlString)
}
```

and then the decode function will come up with the following error:

`/Users/matthijsotterloo/git/CaptureCamera/PhotoSharing/SharingService.swift:63:24: Cannot convert value of type '(String, id: Int, urlString: String?) -> Sharing' to expected argument type '_ -> _ -> _ -> Sharing'`

Anyone knows how to solve this? Thanks in advance.

**Comment by jakecraige** [comment]
Hey there, that error pops up because they have decided to remove the function currying syntax for Swift 3.0, you can read about that change [here](https://github.com/apple/swift-evolution/blob/d709546002e1636a10350d14da84eb9e554c3aac/proposals/0002-remove-currying.md). Because of that, it makes implementing currying in Swift a bit more of a pain. That being said, here's two different ways to get around it.

The first being to use currying how you have to use it in Swift now. Which would look like so:

```swift
static func create(_ api_key: String) -> ((Int) -> ((String?) -> Sharing)) {
    return { id in 
        { urlString in 
            return Sharing(api_key: api_key, id: String(id), urlString: urlString)
        }
    }
}
```

It's a little gnarly to read and maintain, but it should work.

The other option (which is what we typically do at thoughtbot), is to use our library [Curry](https://github.com/thoughtbot/Curry) to handle it for you. With it, you don't even need to create the `create` function(assuming `Sharing` is a struct or has an initializer like you've defined like `create`) and using it would look like:

```swift
import Curry
// ...
static func decode(j: JSON) -> Decoded<Sharing> {
    return curry(Sharing.init)
        <^> j <| "api_key"
        <*> j <| "id"
        <*> j <|? "urlString"
}
```

Let me know if those work for you.

We also have a blog post that goes deeper into what currying is and how it works in Swift [here](https://robots.thoughtbot.com/introduction-to-function-currying-in-swift). It's slightly out of date where it mentions the old syntax but it mostly talks about how to do it the way I did above.

**Comment by gfontenot** [comment]
fwiw, you don't _need_ all of those parens in your curried function if you don't want them. This will compile just fine:

```swift
static func create(_ api_key: String) -> (Int) -> (String?) -> Sharing {
    return { id in 
        { urlString in 
            return Sharing(api_key: api_key, id: String(id), urlString: urlString)
        }
    }
}
```

I would _highly_ recommend letting `Curry.framework` do this work for you, though.

**Comment by gfontenot** [comment]
@matthijsotterloo Do you still need help on this, or is it OK to close the issue?

**Comment by matthijsotterloo** [comment]
Solved! ;)
