### ISSUE TITLE
Problem with the way we use .optional

### ISSUE THREAD

**Issue by pteasima** [thoughtbot/Argo#401]
Hi, I've always loved the simplicity of argo's implementation. However I dont think that we can implement the optional decode operators (`<|?`, `<||?`) just by wrapping the non-optional implementation (`<|`, `<||`) in a `.optional` call. The problem is that the behavior doesnt match the documentation. I believe that the documentation describes the desired behavior, but Im not sure if it can be easily achieved. For simplicity, I will only describe the single value case (`<|?`).

The documentation states:

_This operator is used to decode an optional value from the `JSON`. If the key
isn't present in the `JSON`, this will still return `.Success`. However, if
the key exists **but the object assigned to that key is unable to be decoded**
into the requested type, this will return `.Failure`._

However, if the key is present and the mapping fails with a `.MissingKey` error, the `<|?` operator returns `.Success(nil)`. This is clearly in conflict with the documentation, and the (in my opinion) expected behaviour.
### Sample JSON

```
{
  "child": "anyValue"
}
```
### Models

```
struct Parent {
  let child: Child?
}

extension Parent: Decodable {
  static func decode(json: JSON) -> Decoded<Parent> {
       return curry(self.init)
       <^> json <|? "child"
}

struct Child { }
extension Child: Decodable {
  static func decode(json: JSON) -> Decoded<Child> {
       return .Failure(.MissingKey("this mapping always fails"))
}
```

Trying to decode a `Parent` from the example JSON would return a `Parent` with `.child` set to nil, but should instead return a `Failure(MissingKey)`.

I understand that this limitation may have been done to keep the implementation simple, but the least we should do is update the documentation to describe the actual behaviour.

I wonder if you guys have thought about a proper solution to this. At first thought I feel like we need to report more info in the Errors, to be able to distinguish _at which level_ the .MissingKey error happened. I have long been in favour of including the whole JSON object in the error, I wonder if this would help and if this would be enough. I still think that we wouldnt be able to use the `.optional` function as we currently do, and would need to add extra check to the `<|?` and `<||?` functions.

_Argo 3.1.0_
_Cocoapods_

**Comment by tonyd256** [comment]
@pteasima ... wow it took me quite a while to understand the issue here and I didn't even get it until I started typing a response. This is incredible subtle but I see what you mean. I'm going to think about solutions for a bit and I'll get back to you.

**Comment by gfontenot** [comment]
What's the verdict here?

**Comment by tonyd256** [comment]
@pteasima Sorry for the long delay but I think I have a fix in the works. Check out PR #413. I think this is a fix for the bug you are describing.

**Comment by liscio** [comment]
The fix for this issue caused me a bit of grief this morning, so for the sake of posterity I'm sharing the "workaround" (read: solution?) I came up with…

I am decoding JSON that doesn't have any kind of structure of its own, similar to the following:

``` json
{
  "name" : "Bill",
  "number" : "7",
  "groupName" : "Admin",
  "groupId" : "42",
}
```

I want to turn the above into the following structs that "create structure" out of the enclosing JSON data:

``` swift
struct Group {
  var name: String
  var id: Int
}

struct User {
  var name: String
  var number: Int
  var group: Group?
}
```

Note that the group is optional, and we might be missing the keys that define the group of a given user. We would have otherwise ended up with a Decodable implementation like this:

``` swift
extension Group: Decodable {
  public static func decode(_ j: JSON) -> Decoded<Group> {
    return curry(self.init)
      <^> j <| "groupName"
      <*> j <| "groupId"
  }
}

extension User: Decodable {
  public static func decode(_ j: JSON) -> Decoded<User> {
    return curry(self.init)
      <^> j <| "name"
      <*> j <| "number"
      <*> .optional(Group.decode(j)) // No longer possible
  }
}
```

Unfortunately, after applying the aforementioned PR things started to fail for me because it was otherwise OK to be missing the keys that define the Group, as it just denotes a nil group in the model. To cope with this, I had to adjust my implementation to look more like the following:

``` swift
extension Group: Decodable {
  public static func decode(_ j: JSON) -> Decoded<Group?> {
    let result = curry(self.init)
      <^> j <| "groupName"
      <*> j <| "groupId"
    return .success(result.value)
  }
}

extension User: Decodable {
  public static func decode(_ j: JSON) -> Decoded<User> {
    return curry(self.init)
      <^> j <| "name"
      <*> j <| "number"
      <*> Group.decode(j)
  }
}
```

Note that I switched the above implementation of `Group.decode` so that it now returns an optional `Group`, and force a `.success`ful return value that may now be nil.

Please let me know if I'm missing something obvious in my application of the API above, and forgive any browser coding errors.

Hope this helps!

**Comment by gfontenot** [comment]
Wow, I don't like that at all. The former is what I would expect to work. The latter feels gross. The Group shouldn't care about how it's being stored in the parent, which it now does.

**Comment by liscio** [comment]
I'm glad I shared, then! 😄 

I don't have the mental bandwidth to actually figure out the internals, but it *seems* like this could be resolved by a similar `.optional`-like static function that effectively replicates my forced .success path. 

Another workaround would be to just specify `.success(Group.decode(j).value)` in the `User`'s `decode` implementation. At least that fixes the leaky abstraction, anyway…

**Comment by liscio** [comment]
> I don't have the mental bandwidth to actually figure out the internals

OK so scratch that. This isn't rocket science, really. We can restore `.optional` as it was previously defined, and do nothing else. Everything else has been fixed correctly by not actually using `.optional` where it is inappropriate (AFAICT).

**Comment by tonyd256** [comment]
Ah interesting. I was a bit worried removing `.optional` would mess something up. I removed it because we were no longer using it in Argo but looks like it can be useful. I'll add it back in and release a new version! yay!

**Comment by tonyd256** [comment]
@liscio There is a PR #420 ... would you mind trying that out and make sure that works for you. I'm actually not sure that this new `.optional` is "correct". With the introduction of `.multiple`, we may need to check if everything inside is `.missingKey` and allow that to be `.success(.none)` as well.

**Comment by liscio** [comment]
@tonyd256 Yes, you called it—`.multiple` is giving me grief now.

**Comment by tonyd256** [comment]
>we may need to check if everything inside is `.missingKey` and allow that to be `.success(.none)` as well.

@liscio do you think that will fix it?

**Comment by liscio** [comment]
@tonyd256 Without having much overall understanding of the internals/etc then it's hard for me to make a prescription. I would _think_ that the above should work but then again I incorrectly assumed `.optional` would have done the trick at first glance, so… 😄

**Comment by tonyd256** [comment]
What if `.optional` always didn't care? What if we change it's name to something like `.ignore` and it will return `.success` no matter what.

My thinking is that `.optional` really had no use anymore not that we've fixed the optional parsing. However, there are times like you're experiencing when you really never care if it failed or not and you want to force ignore a failure. It would effectively do exactly what you did in your second code example.

Thoughts? @gfontenot

**Comment by liscio** [comment]
I think that you're right that `.optional` probably shouldn't care. That is, `.optional` can simply be implemented as `return .success(x.value)` where the inner failures get wrapped as `nil` when an error is encountered.

That said, you raise a good point about `.optional` perhaps introducing confusion to those that may have relied on its error handling. For what its worth, I didn't even think about it possibly raising any errors until I looked under the hood.

Personally, I liked the `.optional` naming because it nicely expressed that "this is an optional parameter", or "this is an optional step in the decoding process". The implementation I suggested above seems to fit with the behavior that errors are ignored & turned into nil values (like the `try?` operator.)

**Comment by gfontenot** [comment]
I'm +1 on simplifying `.optional`. It was always complicated to reason about, and I like the idea that it's a simple synonym for forcing `.success`. I'm also +1 on keeping the name `.optional` for legacy reasons, as well as for semantic naming reasons.

**Comment by tonyd256** [comment]
I agree. Updated this branch with that!

**Comment by gfontenot** [comment]
I believe this is now resolved. We've simplified the behavior of `.optional` and I think it's much clearer how it is intended to work. Please feel free to re-open if this isn't the case.
