### ISSUE TITLE
Does Argo Support Failable Initializers?

### ISSUE THREAD

**Issue by possen** [thoughtbot/Argo#456]
Getting a type error with when using a failable initializer. 

### Error Messages

Type does not match. 

### Models

```
import Argo
import Curry
import Runes

struct PhotoSize {
	 let width: Int
	 let height: Int
	 let uri: String
	
	public init?(uri: String, width: Int?, height: Int?) {
		guard uri.characters.count > 0 else {
			return nil
		}
		
		self.uri = uri
		self.height = height ?? Int.max
		self.width = width ?? Int.max
	}
}

extension PhotoSize: Decodable {
    static func decode(_ json: JSON) -> Decoded<PhotoSize> {
        return curry(self.init)
            <^> json <|  "url"
            <*> json <|? "width"
            <*> json <|? "height"
    }
}

```
### Argo Version

 Argo 3.0.0_

### Dependency Manager

Swift Package Manager.

**Comment by gfontenot** [comment]
I wouldn't say that Argo directly "supports" failable initializers, but there's nothing preventing you from using them with Argo, you just need to do some work to get the types to line up.

The specific issue here is that the type of `self.init` in your example is `(String, Int?, Int?) -> PhotoSize?`. That means that the return type of your `decode` function is _actually_ returning `Decoded<PhotoSize?>`, which is why the types aren't lining up here.

I'd suggest _against_ using a failable initializer with Argo (the `Decoded` type includes failure information, or can be transformed into an `Optional` value if needed), but if you _must_ use the failable initializer, you could transform the inner value by passing the whole thing into `Decoded.fromOptional` via `flatMap`:

```diff
 extension PhotoSize: Decodable {
     static func decode(_ json: JSON) -> Decoded<PhotoSize> {
         return curry(self.init)
             <^> json <|  "url"
             <*> json <|? "width"
             <*> json <|? "height"
+            >>- Decoded<PhotoSize>.fromOptional
     }
 }
```

should do the trick

**Comment by possen** [comment]
Thank you! If I could not change the model code for some reason then your second suggested approach looks like it would work. Since I could change it, did as you initially suggested

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
