### ISSUE TITLE
Problem with Decodable on xcode 9

### ISSUE THREAD

**Issue by Gvardia** [thoughtbot/Argo#471]
I was update Xcode to 9 and start to have a problem with compiling project 
![2017-09-25 12 25 30](https://user-images.githubusercontent.com/14106167/30801713-c8906038-a1ec-11e7-8bfb-54f083e65e91.png)
It show on all Decodable file.

**Comment by gfontenot** [comment]
Yeah, sorry about this. I really need to sit down and work on this larger rename, but haven't had any free time for a while.

For now, this error can be fixed by disambiguating the reference to `Decodable`. That means replacing instances of `Decodable` with `Argo.Decodable`. I'm planning on renaming `Decodable` soon, but I'll try to make sure that references to `Argo.Decodable` still resolve properly so that this causes as little pain as possible. The rest of the lib is syntacticly compatible between Swift 3 and Swift 4.

**Comment by Gvardia** [comment]
Thanks It helped. And for those who use Swish it will also help (Swish.Request) Just to notes.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this issue due to inactivity. Feel free to re-open if you'd like to discuss further.
