### ISSUE TITLE
Recursive (boxed) type

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#49]
Using the example from the `README`, how would one set up decoding of `bestFriend`?

```swift
struct User {
  let id: Int
  let name: String
  let email: String?
  let role: Role
  let companyName: String
  let friends: [User]
  let bestFriend: Box<User>
}
```

**Comment by gfontenot** [comment]
My knee jerk reaction would be to have some kind of `boxValue` function of the type `T -> Box<T>`. With that, you could have the following in your decoder:

```swift
static func decoder(j: JSONValue) -> User? {
  return User.create
    <^> // snip
    <*> (boxValue <^> j <| "best_friend")
}
```

This will wrap the returned `User` object in a `Box` if the parsing succeeds.

You _might_ need parens around the parsing operation. Not 100% sure.

**Comment by gfontenot** [comment]
@paulyoung Did this work for you?

**Comment by paulyoung** [comment]
I tried this but the build step hangs.

Usually when this happens and I'm using Argo it's been because I made a mistake somewhere but I can't see how this time.

**Comment by paulyoung** [comment]
I had an extraneous closing parens. This does in fact work.

**Comment by paulyoung** [comment]
Any advice on how to make this work if `bestFriend` is also optional?

**Comment by gfontenot** [comment]
Wrap the whole expression in `pure` (from Runes), or just wrap it in `.Some`. That ensures that the value is always passed through.

This works because `apply` (`<*>`) attempts to unwrap a value from an optional and then passes it to the function if successful. So in this case, what you want to pass to `apply` is something of the type `Optional<Optional<Box<User>>>`. After `apply` unwraps the single level of `Optional`, the value that will be passed to the `create` function will be `Optional<Box<User>>`, which matches up with your expected type.

We're going to put in a bunch of work on adding an obnoxious amount of documentation to Argo next week. I'm probably going to use this as an example.

**Comment by paulyoung** [comment]
Thanks, will give that a try.

**Comment by hyperspacemark** [comment]
@paulyoung I'm going to assume you got this to work and close this. Feel free to comment again if you're still having trouble.

**Comment by paulyoung** [comment]
@hyperspacemark didn't have chance to try it out yet but will report back either way.

**Comment by paulyoung** [comment]
I didn't run into some issue but couldn't confirm that it was because of a recursive type. The build was hanging which I've experienced before using Argo when I've made other errors.

I've been meaning to create a simple example in order to reproduce.
