### ISSUE TITLE
Xcode 11.0 compatibility issue

### ISSUE THREAD

**Issue by elenipapanik** [thoughtbot/Argo#498]
When I tried to build my application with XCode 11.0 I stumbled upon the following compile error:

### Error Messages

Partial application of 'mutating' method is not allowed

### Models

```
struct Experience {
    let title: String?
    let summary: String?
    let company: String?
    let isCurrent: Bool?
    let startDate: String?
    let endDate: String?
}

extension Experience: Argo.Decodable {
   static func decode(_ json: JSON) -> Decoded<Experience> {
       return curry(self.init)
           <^> json <|?? "title"
           <*> json <|?? "summary"
           <*> json <|?? "company"
           <*> json <|?? "current"
           <*> json <|?? "start_date"
           <*> json <|?? "end_date"
   }
}
```

### Argo Version

Argo 4.1.2

![Screenshot 2019-06-12 at 16 24 28](https://user-images.githubusercontent.com/15321233/59357630-dbae6a00-8d33-11e9-9d7d-c2cd3b5e7335.png)

Any thoughts on fixing it?

**Comment by gfontenot** [comment]
Oh wild. I hope this isn't an intentional change in Swift. I haven't tried pulling Argo into Xcode 11 yet though. The fix for this might be going back to a manual `create` static method that is already curried? I'd really hate to see that though. I'm tempted to see how the next few betas impact this issue before figuring out if we need a fix.

**Comment by jshier** [comment]
This may be fixed by [this PR](https://github.com/apple/swift/pull/25289). It will eventually be part of 5.1 AFAICT.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
