### ISSUE TITLE
Outdated version on CocoaPods master repo

### ISSUE THREAD

**Issue by mkalmes** [thoughtbot/Argo#53]
CocoaPods doesn't know about the current version of Argo. A search for Argo reveals v0.2 as current.

Please update Argo on CocoaPods.

**Comment by gfontenot** [comment]
Since CocoaPods doesn't officially support Swift yet, we aren't pushing new versions to the centralized Podspec repo (Trunk). Until then, Carthage is our recommended solution for installation, or by using the `git` flag in your Podfile.

I understand that this causes issues with using Argo as a dependency, but we're waiting on official support from CocoaPods before putting effort into maintaining it as a distribution platform.
