### ISSUE TITLE
JSONDecodable Compile Error

### ISSUE THREAD

**Issue by harinsa** [thoughtbot/Argo#60]
The line below in JSONDecodable.swift caused the error:   
    
    static func decode(JSONValue) -> DecodedType?

    Error: Static methods are only allowed within structs and enums; use 'class' to declare a class method

changing static to class like the error said seems to solve the issue.

**Comment by tonyd256** [comment]
@harinsa we made that change (from `class` to `struct`) for Swift 1.2 compatibility. You are seeing that error most likely because you are using the latest version of Argo with Swift 1.1. Please use Argo 0.3.x versions with Swift 1.1 and 0.4.x versions with Swift 1.2. The current latest version of Argo that should be used in Swift 1.1 is 0.3.4.
